# Generated by Django 4.0.6 on 2022-07-08 18:31

from django.db import migrations, models
import gallery.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=gallery.models.get_upload_file_name),
        ),
    ]
